### ISSUE TITLE
currently not pretty secure

### ISSUE THREAD

**Issue by DO1JLR** [maxbachmann/role-server-security#2]
deploying this role ( 15d908e6229febc1f63cdea4597506ec81618cbf ) dosen't make any effects on my server. They are still unsecured and widely open to all :-/

**Comment by maxbachmann** [comment]
!! Do not use this role !!
I did not have time to finish it (it does pretty much nothing right now

**Comment by DO1JLR** [comment]
Damm.

And I already deployed it on all systems and removed all other security mechanismen like fail to ban or using ssh instead of telnet.
